/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[slug]': RouteRecordInfo<
      '/[slug]',
      '/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | '/[slug]/'
      | '/[slug]/members'
      | '/[slug]/settings'
    >,
    '/[slug]/': RouteRecordInfo<
      '/[slug]/',
      '/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/[slug]/members': RouteRecordInfo<
      '/[slug]/members',
      '/:slug/members',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/[slug]/settings': RouteRecordInfo<
      '/[slug]/settings',
      '/:slug/settings',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/communities/': RouteRecordInfo<
      '/communities/',
      '/communities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/communities/new': RouteRecordInfo<
      '/communities/new',
      '/communities/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/join/[token]': RouteRecordInfo<
      '/join/[token]',
      '/join/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[slug].vue': {
      routes:
        | '/[slug]'
        | '/[slug]/'
        | '/[slug]/members'
        | '/[slug]/settings'
      views:
        | 'default'
      pathParamNames:
        | 'slug'
    }
    'src/pages/[slug]/index.vue': {
      routes:
        | '/[slug]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[slug]/members.vue': {
      routes:
        | '/[slug]/members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[slug]/settings.vue': {
      routes:
        | '/[slug]/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/communities/index.vue': {
      routes:
        | '/communities/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/communities/new.vue': {
      routes:
        | '/communities/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/join/[token].vue': {
      routes:
        | '/join/[token]'
      views:
        | never
      pathParamNames:
        | 'token'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
