/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/c/[slug]': RouteRecordInfo<
      '/c/[slug]',
      '/c/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | '/c/[slug]/'
      | '/c/[slug]/lab/'
      | '/c/[slug]/lab/[game]/'
      | '/c/[slug]/lab/[game]/tips/[userId]'
      | '/c/[slug]/members'
      | '/c/[slug]/profile'
      | '/c/[slug]/requests'
      | '/c/[slug]/rounds/[roundNumber]/tips/[userId]'
      | '/c/[slug]/settings'
    >,
    '/c/[slug]/': RouteRecordInfo<
      '/c/[slug]/',
      '/c/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/c/[slug]/lab/': RouteRecordInfo<
      '/c/[slug]/lab/',
      '/c/:slug/lab',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/c/[slug]/lab/[game]/': RouteRecordInfo<
      '/c/[slug]/lab/[game]/',
      '/c/:slug/lab/:game',
      { slug: ParamValue<true>, game: ParamValue<true> },
      { slug: ParamValue<false>, game: ParamValue<false> },
      | never
    >,
    '/c/[slug]/lab/[game]/tips/[userId]': RouteRecordInfo<
      '/c/[slug]/lab/[game]/tips/[userId]',
      '/c/:slug/lab/:game/tips/:userId',
      { slug: ParamValue<true>, game: ParamValue<true>, userId: ParamValue<true> },
      { slug: ParamValue<false>, game: ParamValue<false>, userId: ParamValue<false> },
      | never
    >,
    '/c/[slug]/members': RouteRecordInfo<
      '/c/[slug]/members',
      '/c/:slug/members',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/c/[slug]/profile': RouteRecordInfo<
      '/c/[slug]/profile',
      '/c/:slug/profile',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/c/[slug]/requests': RouteRecordInfo<
      '/c/[slug]/requests',
      '/c/:slug/requests',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/c/[slug]/rounds/[roundNumber]/tips/[userId]': RouteRecordInfo<
      '/c/[slug]/rounds/[roundNumber]/tips/[userId]',
      '/c/:slug/rounds/:roundNumber/tips/:userId',
      { slug: ParamValue<true>, roundNumber: ParamValue<true>, userId: ParamValue<true> },
      { slug: ParamValue<false>, roundNumber: ParamValue<false>, userId: ParamValue<false> },
      | never
    >,
    '/c/[slug]/settings': RouteRecordInfo<
      '/c/[slug]/settings',
      '/c/:slug/settings',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/communities/': RouteRecordInfo<
      '/communities/',
      '/communities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/communities/new': RouteRecordInfo<
      '/communities/new',
      '/communities/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/join/[token]': RouteRecordInfo<
      '/join/[token]',
      '/join/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/super-admin': RouteRecordInfo<
      '/super-admin',
      '/super-admin',
      Record<never, never>,
      Record<never, never>,
      | '/super-admin/'
      | '/super-admin/communities'
      | '/super-admin/users/'
      | '/super-admin/users/[id]'
    >,
    '/super-admin/': RouteRecordInfo<
      '/super-admin/',
      '/super-admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/super-admin/communities': RouteRecordInfo<
      '/super-admin/communities',
      '/super-admin/communities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/super-admin/users/': RouteRecordInfo<
      '/super-admin/users/',
      '/super-admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/super-admin/users/[id]': RouteRecordInfo<
      '/super-admin/users/[id]',
      '/super-admin/users/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/c/[slug].vue': {
      routes:
        | '/c/[slug]'
        | '/c/[slug]/'
        | '/c/[slug]/lab/'
        | '/c/[slug]/lab/[game]/'
        | '/c/[slug]/lab/[game]/tips/[userId]'
        | '/c/[slug]/members'
        | '/c/[slug]/profile'
        | '/c/[slug]/requests'
        | '/c/[slug]/rounds/[roundNumber]/tips/[userId]'
        | '/c/[slug]/settings'
      views:
        | 'default'
      pathParamNames:
        | 'slug'
    }
    'src/pages/c/[slug]/index.vue': {
      routes:
        | '/c/[slug]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/c/[slug]/lab/index.vue': {
      routes:
        | '/c/[slug]/lab/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/c/[slug]/lab/[game]/index.vue': {
      routes:
        | '/c/[slug]/lab/[game]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/c/[slug]/lab/[game]/tips/[userId].vue': {
      routes:
        | '/c/[slug]/lab/[game]/tips/[userId]'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/pages/c/[slug]/members.vue': {
      routes:
        | '/c/[slug]/members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/c/[slug]/profile.vue': {
      routes:
        | '/c/[slug]/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/c/[slug]/requests.vue': {
      routes:
        | '/c/[slug]/requests'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/c/[slug]/rounds/[roundNumber]/tips/[userId].vue': {
      routes:
        | '/c/[slug]/rounds/[roundNumber]/tips/[userId]'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/pages/c/[slug]/settings.vue': {
      routes:
        | '/c/[slug]/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/communities/index.vue': {
      routes:
        | '/communities/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/communities/new.vue': {
      routes:
        | '/communities/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/join/[token].vue': {
      routes:
        | '/join/[token]'
      views:
        | never
      pathParamNames:
        | 'token'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/super-admin.vue': {
      routes:
        | '/super-admin'
        | '/super-admin/'
        | '/super-admin/communities'
        | '/super-admin/users/'
        | '/super-admin/users/[id]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/super-admin/index.vue': {
      routes:
        | '/super-admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/super-admin/communities.vue': {
      routes:
        | '/super-admin/communities'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/super-admin/users/index.vue': {
      routes:
        | '/super-admin/users/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/super-admin/users/[id].vue': {
      routes:
        | '/super-admin/users/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
