spring:
  application:
    name: core
  modulith:
    runtime:
      flyway-enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liQzcbT4kLUIXWoo
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
  session:
    jdbc:
      initialize-schema: never

app:
  super-admin-github-logins: ${SUPER_ADMIN_GITHUB_LOGINS:}
